#!/usr/bin/env bash
# Local SQL test runner: spins up a throw-away Postgres, replays the repo migrations on top of
# a Supabase stub, then runs every supabase/tests/[1-9]*.sql file. No Supabase project, no
# network, no secrets. Requires a local PostgreSQL 15+ install (initdb, pg_ctl, psql).
#
#   supabase/tests/run_local.sh            # run everything
#   KEEP=1 supabase/tests/run_local.sh     # keep the cluster running afterwards (prints the port)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PG_BIN="${PG_BIN:-}"
if [ -z "$PG_BIN" ]; then
  for d in /opt/homebrew/opt/postgresql@16/bin /usr/local/opt/postgresql@16/bin /usr/lib/postgresql/16/bin; do
    [ -x "$d/initdb" ] && PG_BIN="$d" && break
  done
fi
[ -n "$PG_BIN" ] || PG_BIN="$(dirname "$(command -v initdb)")"

PORT="${PGPORT_LOCAL:-54329}"
TMP="$(mktemp -d)"
DB=concierge_test
cleanup() {
  if [ "${KEEP:-0}" != "1" ]; then
    "$PG_BIN/pg_ctl" -D "$TMP/data" -m fast stop >/dev/null 2>&1 || true
    rm -rf "$TMP"
  else
    echo "Cluster kept: psql -h 127.0.0.1 -p $PORT -U postgres $DB   (data dir: $TMP)"
  fi
}
trap cleanup EXIT

export LC_ALL=C LANG=C
# TCP on loopback only (a unix socket inside a long temp path can exceed the 103-byte limit).
"$PG_BIN/initdb" -D "$TMP/data" -U postgres --auth=trust -E UTF8 --locale=C >/dev/null
"$PG_BIN/pg_ctl" -D "$TMP/data" -o "-p $PORT -c listen_addresses=127.0.0.1 -c unix_socket_directories=''" -l "$TMP/pg.log" -w start >/dev/null
PSQL=("$PG_BIN/psql" -h 127.0.0.1 -p "$PORT" -U postgres -v ON_ERROR_STOP=1 -q)
"${PSQL[@]}" -d postgres -c "CREATE DATABASE $DB"

sed "s/CURRENT_DATABASE_PLACEHOLDER/$DB/" "$ROOT/supabase/tests/00_supabase_stub.sql" | "${PSQL[@]}" -d "$DB" >/dev/null

# Legacy migrations (before STRICT_FROM) were generated by Lovable and are not replayable from
# an empty database (e.g. `profiles` is created twice); they run tolerantly so the schema they
# do manage to build exists. Everything from STRICT_FROM on must apply cleanly.
# Migrations that need Supabase-only extensions (pgvector) are skipped locally.
STRICT_FROM="${STRICT_FROM:-20260715}"
SKIP_RE='1a6522ab-b8b2-464f-9932-da87c7f50443'
for f in "$ROOT"/supabase/migrations/*.sql; do
  b="$(basename "$f")"
  if [[ "$b" =~ $SKIP_RE ]]; then echo "skip  $b (needs pgvector)"; continue; fi
  if [[ "${b:0:8}" < "$STRICT_FROM" ]]; then
    errs=$("${PSQL[@]}" -v ON_ERROR_STOP=0 -d "$DB" -f "$f" 2>&1 >/dev/null | grep -c "ERROR" || true)
    echo "legacy $b (tolerated errors: $errs)"
  else
    if [ -z "${FIXUPS_DONE:-}" ]; then
      "${PSQL[@]}" -d "$DB" -f "$ROOT/supabase/tests/01_legacy_fixups.sql" >/dev/null
      FIXUPS_DONE=1
    fi
    echo "apply $b"
    "${PSQL[@]}" -d "$DB" -f "$f" >/dev/null
  fi
done

fail=0
for t in "$ROOT"/supabase/tests/[1-9]*.sql; do
  [ -e "$t" ] || continue
  echo "test  $(basename "$t")"
  if ! "${PSQL[@]}" -d "$DB" -f "$t"; then fail=1; echo "FAILED $(basename "$t")"; fi
done
[ "$fail" = 0 ] && echo "ALL SQL TESTS PASSED" || { echo "SQL TESTS FAILED"; exit 1; }
