project_id = "jybewogjncaoscrnlqum"

[functions.mailing-list-signup]
verify_jwt = false

[functions.newsletter-subscribe]
verify_jwt = false

[functions.resend-access-link]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = true

[functions.resend-test-email]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = true