import { unwrap } from "./db.ts";
import { defineTool, ToolError } from "./types.ts";

const MAX_ACTIONS = 20;

interface ReportRow {
  id: string;
  period_start: string;
  period_end: string;
  kpi_snapshot: unknown;
  diagnostic_narrative: string;
  generated_at: string;
}

interface ActionRow {
  id: string;
  kind: "urgent" | "strategic";
  number: number;
  action_text: string;
  done: boolean;
}

/** Owner-only: the most recent "lettura del centro" (P1.6) generated by generate-report. */
export const getLatestReport = defineTool<Record<string, never>>({
  name: "get_latest_report",
  description:
    "Restituisce l'ultimo referto generato per il centro (la lettura di benessere aziendale): " +
    "periodo, indicatori con semaforo, commento diagnostico e le azioni urgenti/strategiche con " +
    "il loro stato. Usalo quando l'utente chiede del referto o delle azioni consigliate.",
  parameters: { type: "object", properties: {}, additionalProperties: false },
  access: "owner",
  write: false,
  async handler({ supabase, centerId }) {
    const report = unwrap<ReportRow>(
      await supabase
        .from("center_reports")
        .select("id, period_start, period_end, kpi_snapshot, diagnostic_narrative, generated_at")
        .eq("center_id", centerId)
        .order("generated_at", { ascending: false })
        .limit(1)
        .maybeSingle(),
    );
    if (!report) throw new ToolError("not_found", "Nessun referto ancora generato per questo centro");

    const actions = unwrap<ActionRow[]>(
      await supabase
        .from("center_actions")
        .select("id, kind, number, action_text, done")
        .eq("report_id", report.id)
        .order("kind")
        .order("number")
        .limit(MAX_ACTIONS),
    ) ?? [];

    return {
      report,
      urgent_actions: actions.filter((a) => a.kind === "urgent"),
      strategic_actions: actions.filter((a) => a.kind === "strategic"),
    };
  },
});
